//    Roxy Pos  - Touch Friendly Point Of Sale
//    Copyright (c)  uniCenta & previous Openbravo POS works
//    https://unicenta.com
//
//    This file is part of Roxy Pos
//
//    Roxy Pos is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//   Roxy Pos is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Roxy Pos.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.data.gui;

import java.util.*;
import javax.swing.*;
import com.openbravo.basic.BasicException;
import com.openbravo.data.loader.LocalRes;
import com.openbravo.data.user.BrowsableEditableData;
import com.openbravo.data.user.StateListener;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.DataLogicSystem;
import com.openbravo.pos.printer.DeviceTicket;

/**
 *
 * @author JG uniCenta
 */
public class JCashDrawer extends JPanel implements StateListener {
    
    /**
     *
     */
    private DataLogicSystem dlSystem;    
    private DeviceTicket mDevice;    
    protected BrowsableEditableData m_bd;
        
    /** Creates new form JSaver
     * @param bd */
    public JCashDrawer(AppView appview, BrowsableEditableData bd) {

        initComponents();
        
        m_bd = bd;
        m_bd.addStateListener(this);
        mDevice = new DeviceTicket();
        dlSystem = (DataLogicSystem) appview.getBean("com.openbravo.pos.forms.DataLogicSystem");
    }

    /**
     *
     * @param iState
     */
    @Override
    public void updateState(int iState) {
        jbtnCashDrawer.setEnabled(true);
   }   
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnCashDrawer = new javax.swing.JButton();

        jbtnCashDrawer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/cashdrawer.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pos_messages"); // NOI18N
        jbtnCashDrawer.setToolTipText(bundle.getString("tooltip.opencashdrawer")); // NOI18N
        jbtnCashDrawer.setFocusPainted(false);
        jbtnCashDrawer.setFocusable(false);
        jbtnCashDrawer.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jbtnCashDrawer.setPreferredSize(new java.awt.Dimension(60, 45));
        jbtnCashDrawer.setRequestFocusEnabled(false);
        jbtnCashDrawer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCashDrawerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnCashDrawer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbtnCashDrawer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCashDrawerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCashDrawerActionPerformed
        mDevice.getDevicePrinter("1").openDrawer();
    }//GEN-LAST:event_jbtnCashDrawerActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCashDrawer;
    // End of variables declaration//GEN-END:variables
    
}
