//    Roxy Pos  - Touch Friendly Point Of Sale
//    Copyright © 2009-2020 uniCenta & previous Openbravo POS works
//    https://unicenta.com
//
//    This file is part of Roxy Pos
//
//    Roxy Pos is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//   Roxy Pos is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Roxy Pos.  If not, see <http://www.gnu.org/licenses/>.

package com.openbravo.pos.catalog;

import com.openbravo.beans.JFlowPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.border.Border;

/**
 *
 * @author adrianromero
 */
public class JCatalogTab extends javax.swing.JPanel {
    
    public JFlowPanel flowpanel;
    
    /** Creates new form JCategoryProducts */
    public JCatalogTab() {
        initComponents();

        flowpanel = new JFlowPanel();
        JScrollPane scroll = new JScrollPane(flowpanel);
        scroll.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scroll.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        //scroll.setBorder(BorderFactory.createMatteBorder(2, 0, 0, 0, Color.CYAN));
        scroll.getVerticalScrollBar().setPreferredSize(new Dimension(35, 35));
        
        add(scroll, BorderLayout.CENTER);
    }
    
    @Override
    public void setEnabled(boolean value) {
        flowpanel.setEnabled(value);
        super.setEnabled(value);
    }

    /**
     *
     * @param ico
     * @param al
     * @param textTip
     */
        public void addButton(Icon ico, ActionListener al, String textTip) {
            JButton btn = new JButton();
            btn.applyComponentOrientation(getComponentOrientation());
            btn.setIcon(ico);
            btn.setFocusPainted(false);
            btn.setFocusable(false);

            if (textTip != null){
                btn.setToolTipText(textTip);
            }

            btn.setRequestFocusEnabled(false);
            btn.setHorizontalTextPosition(SwingConstants.CENTER);
            btn.setVerticalTextPosition(SwingConstants.BOTTOM);
            btn.setMargin(new Insets(2, 2, 2, 2));
            btn.setPreferredSize(new Dimension(116, 60));
            //btn.setFont(new java.awt.Font("Tahoma", 0, 12));
            btn.setForeground(Color.WHITE);
            btn.addActionListener(al);

            flowpanel.add(btn);        
    }
    
    /**
     *
     * @param ico
     * @param al
     * @param textTip
     */
        public void addBackButton(ActionListener al) {
            JButton btn = new JButton();
            btn.applyComponentOrientation(getComponentOrientation());
            btn.setText("Back");
            btn.setFocusPainted(false);
            btn.setFocusable(false);
            btn.setRequestFocusEnabled(false);
            btn.setHorizontalTextPosition(SwingConstants.CENTER);
            btn.setVerticalTextPosition(SwingConstants.BOTTOM);
            btn.setMargin(new Insets(2, 2, 2, 2));
            btn.setPreferredSize(new Dimension(116, 60));
            btn.addActionListener(al);

            flowpanel.add(btn);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        button1 = new java.awt.Button();
        panel18 = new java.awt.Panel();
        panel3 = new java.awt.Panel();
        panel4 = new java.awt.Panel();
        panel5 = new java.awt.Panel();
        panel6 = new java.awt.Panel();
        panel7 = new java.awt.Panel();
        panel8 = new java.awt.Panel();
        panel9 = new java.awt.Panel();
        panel10 = new java.awt.Panel();
        panel11 = new java.awt.Panel();
        panel12 = new java.awt.Panel();
        panel13 = new java.awt.Panel();
        panel14 = new java.awt.Panel();
        panel15 = new java.awt.Panel();
        panel16 = new java.awt.Panel();
        panel17 = new java.awt.Panel();

        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setLayout(new java.awt.BorderLayout());

        panel1.setLayout(new java.awt.GridLayout(0, 6));

        panel2.setName(""); // NOI18N
        panel2.setPreferredSize(new java.awt.Dimension(100, 100));

        button1.setLabel("button1");
        panel2.add(button1);

        panel18.setPreferredSize(new java.awt.Dimension(110, 30));
        panel2.add(panel18);

        panel1.add(panel2);

        panel3.setName(""); // NOI18N
        panel3.setPreferredSize(new java.awt.Dimension(100, 200));
        panel1.add(panel3);

        panel4.setName(""); // NOI18N
        panel4.setPreferredSize(new java.awt.Dimension(100, 100));
        panel1.add(panel4);

        panel5.setName(""); // NOI18N
        panel5.setPreferredSize(new java.awt.Dimension(100, 200));
        panel1.add(panel5);

        panel6.setName(""); // NOI18N
        panel6.setPreferredSize(new java.awt.Dimension(100, 100));
        panel1.add(panel6);

        panel7.setName(""); // NOI18N
        panel7.setPreferredSize(new java.awt.Dimension(100, 200));
        panel1.add(panel7);

        panel8.setName(""); // NOI18N
        panel8.setPreferredSize(new java.awt.Dimension(100, 100));
        panel1.add(panel8);

        panel9.setName(""); // NOI18N
        panel9.setPreferredSize(new java.awt.Dimension(100, 200));
        panel1.add(panel9);

        panel10.setName(""); // NOI18N
        panel10.setPreferredSize(new java.awt.Dimension(100, 100));
        panel1.add(panel10);

        panel11.setName(""); // NOI18N
        panel11.setPreferredSize(new java.awt.Dimension(100, 200));
        panel1.add(panel11);

        panel12.setName(""); // NOI18N
        panel12.setPreferredSize(new java.awt.Dimension(100, 100));
        panel1.add(panel12);

        panel13.setName(""); // NOI18N
        panel13.setPreferredSize(new java.awt.Dimension(100, 200));
        panel1.add(panel13);

        panel14.setName(""); // NOI18N
        panel14.setPreferredSize(new java.awt.Dimension(100, 100));
        panel1.add(panel14);

        panel15.setName(""); // NOI18N
        panel15.setPreferredSize(new java.awt.Dimension(100, 200));
        panel1.add(panel15);

        panel16.setName(""); // NOI18N
        panel16.setPreferredSize(new java.awt.Dimension(100, 100));
        panel1.add(panel16);

        panel17.setName(""); // NOI18N
        panel17.setPreferredSize(new java.awt.Dimension(100, 200));
        panel1.add(panel17);

        jScrollPane1.setViewportView(panel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel10;
    private java.awt.Panel panel11;
    private java.awt.Panel panel12;
    private java.awt.Panel panel13;
    private java.awt.Panel panel14;
    private java.awt.Panel panel15;
    private java.awt.Panel panel16;
    private java.awt.Panel panel17;
    private java.awt.Panel panel18;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private java.awt.Panel panel7;
    private java.awt.Panel panel8;
    private java.awt.Panel panel9;
    // End of variables declaration//GEN-END:variables
    
}
